### PR TITLE
Adding DIS Plotting scripts

### PR DESCRIPTION
**Pull request by MarcCastro623**
Here is my code for th DIS kinematics. I am having trouble saving the plots as pictures.

### CODE REVIEW

**Comment by mariakzurek** [comment]
Please add prtscrs.

**Review by mariakzurek — APPROVED** [review]

**Comment by MarcCastro623** [comment]
Q2VsX
RapidityVsQ2
Q2VsInelasticity
InelasticityVsX
EnergyVsAngle

here are the 5 plots I made from the script.

**Comment by mariakzurek** [comment]
Fantastic!

**Comment by MarcCastro623** [comment]
EnergyVsAngleDeg
here's the scattered electron energy vs theta in degrees plot. The plots of theta in rad and degrees look the same.

**Comment by MarcCastro623** [comment]
I improved the Scattered Ene vs Angle plot to highlight the range our calorimeter will detect.
EneVsAng

**Comment by mariakzurek** [comment]
Marc, in the first plot your x is > 1. This cannot be, x should be 0 < x < 1. Please correct.

**Comment by MarcCastro623** [comment]
Fixed it. Good luck on the presentation
Q^2vsXfixed

**Pull request merged**
